import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Footer from '../components/footer'
export default function Home() {
  return (
    <div className='dark:bg-gray-900 bg-gray-50'>
      <Head>
        <title>Data Science Association</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar />
      <section className="text-gray-600 lg:py-20 md:py-60 py-5 h-[100vh] body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
            <span className={`text-8xl opacity-80 title text-gray-500 dark:text-white`}>D.S.S.A</span><span className={`text-7xl opacity-80 title text-gray-500 dark:text-white`}>Association</span>
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-500 dark:text-white">Before they sold out
              <br className="hidden lg:inline-block" />readymade gluten
            </h1>
            <p className="mb-8 leading-relaxed text-gray-500 dark:text-white">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
            <div className="flex justify-center">
              <button className="inline-flex text-gray-500 dark:text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
            </div>
          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            <img className="object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600" />
          </div>
        </div>
      </section>
      <section className=' pt-20  text-center'>
        <div className='md:px-20 px-5 py-10'>
          <span className={`text-6xl dark:opacity-72 title text-center`}>Student Life @ Saraswati</span>
          <div className='md:px-10 px-1'>
          <h2 className={`text-4xl text-center text-gray-500 dark:text-white lg:px-72 md:40 px-5 relative -top-5`}>
            Know Details About Our Company
          </h2>
          <p className="lg:px-80 md:40 text-gray-500 dark:text-white px-5">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
            convallis tortor eros. Donec vitae tortor lacus. Phasellus aliquam
            ante in maximus.
          </p>
          </div>
          </div>
          <div className="containersport py-20 lg:px-40 md:pt-5 px-5" id="sport1">
            <div className="flex flex-wrap md:-m-2 -m-1">
              <div className="flex flex-wrap w-full md:w-1/3">
              <img src="./landing/athletic-track.jpg" className="w-full md:w-80 h-80 py-2 px-2" alt="..." />
                    <div className="headings4">
                      <h4>Athletics</h4>
                    </div>
              </div>
              <div className="flex flex-wrap w-full md:w-2/3">
              <img src="./landing/football.jpg" className="w-full  h-80 py-2 px-2" alt="..." />
                    <div className="headings4">
                      <h4>Football</h4>
                    </div>
              </div>
              <div className="flex flex-wrap w-full md:w-1/3">
              <img src="./landing/carrom.jpg" className="md:w-80 w-full h-80 py-2 px-2" alt="..." />
                    <div className="headings4">
                      <h4>Carrom</h4>
                    </div>
              </div>
              <div className="flex flex-wrap w-full md:w-1/3">
              <img src="./landing/kho-kho.jpg" className="md:w-80 w-full h-80 py-2 px-2" alt="..." />
                    <div className="headings4">
                      <h4>kho-kho</h4>
                    </div>
              </div>
              <div className="flex flex-wrap w-full md:w-1/3">
              <img src="./landing/basketball.jpg" className="md:w-80 w-full h-80 py-2 px-2" alt="..." />
                    <div className="headings4">
                      <h4>Basketball</h4>
                    </div>
              </div>
              <div className="flex flex-wrap w-full">
              <img src="./landing/cricket.jpg" className="w-full h-80 py-2 px-2" alt="..." />
                    <div className="headings4">
                      <h4>Cricket</h4>
                    </div>
              </div>
            </div>
          </div>
      </section>
      <section>
        <div className="py-10 flex-col  text-center " data-wow-delay=".2s">
          <span className={`text-8xl dark:opacity-72 title text-gray-500 dark:text-white`}>Our Gallery</span>
          <h2 className={`text-4xl text-center text-gray-500 dark:text-white lg:px-72 md:40 px-5 relative -top-5`}>
            Know Details About Our Company
          </h2>
          <p className="lg:px-80 md:40 text-gray-500 dark:text-white px-5">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
            convallis tortor eros. Donec vitae tortor lacus. Phasellus aliquam
            ante in maximus.
          </p>
        </div>
        <section className="text-gray-600 body-font ">
          <div className="container px-5 py-24 mx-auto flex flex-wrap">
            <div className="flex flex-wrap md:-m-2 -m-1">
              <div className="flex flex-wrap w-1/2">
                <div className="md:p-2 p-1 w-1/2">
                  <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/500x300" />
                </div>
                <div className="md:p-2 p-1 w-1/2">
                  <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/501x301" />
                </div>
                <div className="md:p-2 p-1 w-full">
                  <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/600x360" />
                </div>
              </div>
              <div className="flex flex-wrap w-1/2">
                <div className="md:p-2 p-1 w-full">
                  <img alt="gallery" className="w-full h-full object-cover object-center block" src="https://dummyimage.com/601x361" />
                </div>
                <div className="md:p-2 p-1 w-1/2">
                  <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/502x302" />
                </div>
                <div className="md:p-2 p-1 w-1/2">
                  <img alt="gallery" className="w-full object-cover h-full object-center block" src="https://dummyimage.com/503x303" />
                </div>
              </div>
            </div>
          </div>
        </section>
      </section>
      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h2 className="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">REVIEWS</h2>
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-500 dark:text-white">Here are few of the reviews from our users</h1>
          </div>
          <div className="flex flex-wrap -mx-4 -my-8">
            <div className="py-8 px-4 lg:w-1/3">
              <div className="h-full flex items-start border py-5 px-10">
                <div className="w-12 flex-shrink-0 flex flex-col text-center leading-none">
                  <span className="text-gray-500 dark:text-white pb-2 mb-2 border-b-2 border-gray-200">Jul</span>
                  <span className="font-medium text-lg text-gray-500 dark:text-white title-font leading-none">18</span>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="tracking-widest text-xs title-font font-medium tetext-gray-500 dark:text-white mb-1">CATEGORY</h2>
                  <h1 className="title-font text-xl font-medium text-gray-500 dark:text-white mb-3">The 400 Blows</h1>
                  <p className="leading-relaxed mb-5 text-gray-500 dark:text-white">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                  <a className="inline-flex items-center">
                    <span className="flex-grow flex flex-col pl-3">
                      <span className="title-font font-medium text-gray-500 dark:text-white">Alper Kamu</span>
                    </span>
                  </a>
                </div>
              </div>
            </div>
            <div className="py-8 px-4 lg:w-1/3">
              <div className="h-full flex items-start border py-5 px-10">
                <div className="w-12 flex-shrink-0 flex flex-col text-center leading-none">
                  <span className="text-gray-500 dark:text-white pb-2 mb-2 border-b-2 border-gray-200">Jul</span>
                  <span className="font-medium text-lg text-gray-500 dark:text-white title-font leading-none">18</span>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="tracking-widest text-xs title-font font-medium tetext-gray-500 dark:text-white mb-1">CATEGORY</h2>
                  <h1 className="title-font text-xl font-medium text-gray-500 dark:text-white mb-3">The 400 Blows</h1>
                  <p className="leading-relaxed mb-5 text-gray-500 dark:text-white">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                  <a className="inline-flex items-center">
                    <span className="flex-grow flex flex-col pl-3">
                      <span className="title-font font-medium text-gray-500 dark:text-white">Alper Kamu</span>
                    </span>
                  </a>
                </div>
              </div>
            </div>
            <div className="py-8 px-4 lg:w-1/3">
              <div className="h-full flex items-start border py-5 px-10">
                <div className="w-12 flex-shrink-0 flex flex-col text-center leading-none">
                  <span className="text-gray-500 dark:text-white pb-2 mb-2 border-b-2 border-gray-200">Jul</span>
                  <span className="font-medium text-lg text-gray-500 dark:text-white title-font leading-none">18</span>
                </div>
                <div className="flex-grow pl-6">
                  <h2 className="tracking-widest text-xs title-font font-medium tetext-gray-500 dark:text-white mb-1">CATEGORY</h2>
                  <h1 className="title-font text-xl font-medium text-gray-500 dark:text-white mb-3">The 400 Blows</h1>
                  <p className="leading-relaxed mb-5 text-gray-500 dark:text-white">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                  <a className="inline-flex items-center">
                    <span className="flex-grow flex flex-col pl-3">
                      <span className="title-font font-medium text-gray-500 dark:text-white">Alper Kamu</span>
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  )
}
